#!/home/reeves/Enthought/Canopy_32bit/User/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pyuvvis==0.2','console_scripts','gwuspec'
__requires__ = 'pyuvvis==0.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pyuvvis==0.2', 'console_scripts', 'gwuspec')()
    )
